language: ruby
before_script:
  - psql -c 'create database "bundler-api";' -U postgres
  - cp .env.example .env && export $(cat .env) && ./script/setup -v
rvm: 1.9.3
script: export $(cat .env) && rspec
notifications:
  irc:
    on_success: change
    on_failure: always
    channels: "irc.freenode.org#bundler"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "Jba3CyoKcwkuX5Qi4Q8W5XPzQqrRtUMJMIaBLj/FJeJydLiDhtHZanozq7LI\nvOIjJDd7YMh52IB/YwJnp38+3BOY4llRozVqCT1wV/AxLRJMcTeaagbeO11d\nEh0a5LacjdlgYDf7b2AVaErQnwEb9utQQR8byPH6lQy9wXi7JTY="
